### ISSUE TITLE
求更新

### ISSUE THREAD

**Issue by murdonson** [xuzijia/blog#3]
rt (✺ω✺)

**Comment by yihuiluo235** [comment]
这个不是原作者，请不要被骗了。 https://github.com/miyakowork/NoteBlog原作者地址。。
 此作者为剽窃。

**Comment by xuzijia** [comment]
@yihuiluo235 已经在readme.md文件声明了原作者地址了！而且后端程序都是我自己开发的，只是借用了人家的页面模板而已，你怎么可以说我剽窃呢
